//! Various assorted utilities.

use netcanv_renderer::paws::{point, vector, Point, Vector};

//
// Math
//

/// Quantizes the given value, such that it lands only on multiples of `step`.
pub fn quantize(value: f32, step: f32) -> f32 {
   step * (value / step + 0.5).floor()
}

/// Performs linear interpolation between `v0` and `v1` with the provided coefficient `t`.
pub fn lerp(v0: f32, v1: f32, t: f32) -> f32 {
   (1.0 - t) * v0 + t * v1
}

/// Performs linear interpolation between two points.
pub fn lerp_point(p0: Point, p1: Point, t: f32) -> Point {
   point(lerp(p0.x, p1.x, t), lerp(p0.y, p1.y, t))
}

pub trait VectorMath {
   fn round(self) -> Self;
}

impl VectorMath for Vector {
   fn round(self) -> Self {
      vector(self.x.round(), self.y.round())
   }
}

//
// Threads
//

/// A default error generated by a subsystem.
pub struct Error(pub anyhow::Error);

/// A fatal error generated by a subsystem.
///
/// Fatal errors, unlike normal errors, should kick the user out to the lobby, or perform a similar
/// action that would end the connection.
pub struct Fatal(pub anyhow::Error);

/// Catches an error onto the global bus and returns the provided value from the current function.
#[macro_export]
macro_rules! catch {
    ($exp:expr, as $T:expr, return $or:expr $(,)?) => {
        match $exp {
            Ok(ok) => ok,
            Err(err) => {
                nysa::global::push($T(::anyhow::anyhow!(err)));
                return $or
            },
        }
    };

    ($exp:expr, return $or:expr $(,)?) => {
        catch!($exp, as crate::common::Error, return $or)
    };

    ($exp:expr, as $T:expr $(,)?) => {
        catch!($exp, as $T, return ())
    };

    ($exp:expr $(,)?) => {
        catch!($exp, return ())
    };
}
